/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import client.AudioHandler;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import messagetype.AudioMessage;
import messagetype.Message;
import messagetype.StringMessage;

/**
 *
 * @author Administrator
 */
public class showtn extends javax.swing.JPanel {

    /**
     * Creates new form showtn
     */
    static ArrayList<JButton> bt = new ArrayList<>(); 
    static ArrayList<AudioMessage> ms = new ArrayList<>(); 
    
    public showtn(Message as) {
        initComponents();
        jLabel1.setText(as.getUser() + ":");
        if (as instanceof StringMessage){
            StringMessage ms = (StringMessage) as;
            JLabel lb = new JLabel();
            lb.setFont(new Font("Segoe UI", Font.PLAIN, 24));
            lb.setForeground(Color.white);
            lb.setText(ms.getContent());
            jPanel1.add(lb);

            jPanel1.revalidate();
            jPanel1.repaint();
            
            
        }
        else {
            AudioMessage ams = (AudioMessage) as;
            JLabel lb = new JLabel();
            ImageIcon user = new ImageIcon(showtn.class.getResource("/icon/volume-trans.png"));
            lb.setIcon(user);
            lb.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
            AudioHandler.playAudio(ams.getAudio());
            }
            });
            jPanel1.add(lb);

            jPanel1.revalidate();
            jPanel1.repaint();
            
           
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel2");
        add(jLabel1, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
